Fix failing tests
Moonsong-Labs/cairo-bootloader pull request #4
Opened 2024-06-03 15:46 UTC by whichqua

## Type

- [ ] feature
- [ ] bugfix
- [ ] dev (no functional changes, no API changes)
- [ ] fmt (formatting, renaming)
- [ ] build
- [ ] docs
- [x] testing

## Description
This attempts to get all the tests passing.

### Pending Tasks
- [ ] Get all the tests passing.
- [ ] Add sub-module for cairo-programs to allow external deps

## Breaking changes?

- [ ] yes
- [x] no

2024-06-05 16:11 UTC, odesenfans requested changes
Good work! What remains:
1. Seems like you had some issues in your rebase, lots of code that remains from my initial branch but was refactored on `main` in the meantime.
2. Clean up the macros

2024-06-05 16:11 UTC, odesenfans commented on resources/bootloader-0.13.1.json
Remove this file.

2024-06-05 16:11 UTC, odesenfans commented on Cargo.toml
> -
Don't remove newlines at end of files. Configure your IDE to avoid this?

2024-06-05 16:11 UTC, odesenfans commented on Cargo.toml
> +] }
Revert.

2024-06-05 16:11 UTC, odesenfans commented on scripts/compile-bootloader.sh
> +CAIRO_VERSION="0.13.1"
Revert.

2024-06-05 16:11 UTC, odesenfans commented on scripts/compile-bootloader.sh
> +cairo-compile "${CAIRO_LANG_DIR}/src/starkware/cairo/bootloaders/bootloader/bootloader.cairo" --output "${COMPILED_BOOTLOADER}" --cairo_path "${CAIRO_LANG_DIR}"/src
Revert.

2024-06-05 16:11 UTC, odesenfans commented on src/hints/bootloader_hints.rs
> +        vm.add_memory_segment();
This is not implementing the same behavior. You'll need something like:

```
        let output_segment = vm.add_memory_segment();
        let output_builtin = {
            let mut builtin = OutputBuiltinRunner::new(true);
            builtin.new_state(output_segment.segment_index, true);
            builtin
        };
        
        vm.builtin_runners = vec![output_builtin.into()];
```

2024-06-05 16:11 UTC, odesenfans commented on src/hints/bootloader_hints.rs
> +        // let ids_data = ids_data!["n_subtasks"];
Remove commented code.

2024-06-05 16:11 UTC, odesenfans commented on src/hints/bootloader_hints.rs
> +        let new_ap = (*&vm.get_ap() + 1usize).unwrap();
Why `*&`? Seems weird.

```suggestion
        let new_ap = vm.get_ap().offset + 1;
```

2024-06-05 16:11 UTC, odesenfans commented on src/hints/bootloader_hints.rs
> +            cairo_vm::vm::runners::cairo_pie::BuiltinAdditionalData::Output(o) => o.pages,
Maybe `use cairo_vm::vm::runners::cairo_pie::BuiltinAdditionalData;` and shorten this ?

2024-06-05 16:11 UTC, odesenfans commented on src/hints/execute_task_hints.rs
> +        let code_address: Result<Relocatable, MathError> = *&program_header_ptr + header_size;
Okay so a bit of context for this `*&` thing: I used `&Relocatable` before because `cairo-vm` had a weird quirk that addition for `Relocatable` would return a `Result` and `&Relocatable` would return the value directly. This was convenient, but they fixed that and now addition returns a `Result` in all cases.

So I'm pretty sure you can remove `*&` everywhere.

2024-06-05 16:11 UTC, odesenfans commented on src/hints/execute_task_hints.rs
> +        let expected_code_address: Relocatable = code_address.unwrap();
No need to do this in two steps, `let expected_code_address = (program_header_ptr + header_size).unwrap();` should work.

2024-06-05 16:11 UTC, odesenfans commented on src/hints/hint_processor.rs
> +impl ResourceTracker for BootloaderHintProcessor {}
Something is weird, this is duplicated from `main`. I think there was some kind of issue during your rebase. I think you can remove this.

2024-06-05 16:11 UTC, odesenfans commented on src/lib.rs
> +}
Are you using this one? If not, delete it.

2024-06-05 16:11 UTC, odesenfans commented on src/lib.rs
> +macro_rules! ids_data_old {
I guess this is not used? Remove.

2024-06-05 16:11 UTC, odesenfans commented on src/lib.rs
> +macro_rules! ids_data {
Same, can be removed I guess. Most macros in this file are not used and are just copies of what's in `cairo-vm`, clean this up.

2024-06-05 16:11 UTC, odesenfans commented on src/lib.rs
> +macro_rules! vm {
Put the macros in a dedicated file to keep `lib.rs` minimal.

2024-06-06 09:37 UTC, whichqua commented on src/lib.rs
> +macro_rules! ids_data {
But those in cairo-vm are not exposed. This one is used in a few places

2024-06-06 09:55 UTC, whichqua commented on src/hints/execute_task_hints.rs
> +        let expected_code_address: Relocatable = code_address.unwrap();
This fails to compile: `type annotations needed cannot infer type`

2024-06-06 10:02 UTC, whichqua commented on src/lib.rs
> +macro_rules! vm {
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 10:02 UTC, whichqua commented on src/lib.rs
> +macro_rules! ids_data_old {
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 10:02 UTC, whichqua commented on src/lib.rs
> +}
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 10:02 UTC, whichqua commented on src/hints/hint_processor.rs
> +impl ResourceTracker for BootloaderHintProcessor {}
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 10:03 UTC, whichqua commented on src/hints/execute_task_hints.rs
> +        let expected_code_address: Relocatable = code_address.unwrap();
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 10:03 UTC, whichqua commented on src/hints/execute_task_hints.rs
> +        let code_address: Result<Relocatable, MathError> = *&program_header_ptr + header_size;
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 10:03 UTC, whichqua commented on src/hints/bootloader_hints.rs
> +            cairo_vm::vm::runners::cairo_pie::BuiltinAdditionalData::Output(o) => o.pages,
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 10:04 UTC, whichqua commented on src/hints/bootloader_hints.rs
> +        let new_ap = (*&vm.get_ap() + 1usize).unwrap();
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 10:04 UTC, whichqua commented on src/hints/bootloader_hints.rs
> +        // let ids_data = ids_data!["n_subtasks"];
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 10:04 UTC, whichqua commented on src/hints/bootloader_hints.rs
> +        vm.add_memory_segment();
Resolved by https://github.com/Moonsong-Labs/cairo-bootloader/pull/4/commits/81deb991e449e74e7823e73a6a99a0579093f617

2024-06-06 12:49 UTC, odesenfans requested changes
One more macro to remove, all good besides that!

2024-06-06 12:49 UTC, odesenfans commented on src/macros.rs
> +macro_rules! references {
This macro is unused.

2024-06-06 12:59 UTC, odesenfans approved these changes

2024-06-06 13:04 UTC, merged